request:
  kinds_of_periods:
    ticks: 1
    1min: 2
    5min: 3
    10min: 4
    15min: 5
    30min: 6
    H: 7
    D: 8
    W: 9
    M: 10
  period: D
  date_format: 1
  # 1=yyyymmdd
  # 2=yymmdd
  # 3=ddmmyy
  # 4=dd/mm/yy
  # 5=mm/dd/yy
  time_format: 1
  # 1=hhmmss
  # 2=hhmm
  # 3=hh:mm:ss
  # 4=hh:mm
  sep_fields: 3 # 3=; 1=, 2=. 4=\t 5=\space
  sep_digits: 1
  # 1=without separator
  # 2=.
  # 3=,
  # 4=\space
  # 5='
  header: 1
  # 1=ticker, per, date, time, open, high, low, close, vol
  # 2=ticker, per, date, time, open, high, low, close
  # 3=ticker, per, date, time, close, vol
  # 4=ticker, per, date, time, close
  # 5=date, time, open, high, low, close, vol
  # 12=date, time, last, vol, id, open